// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWmaSWoh0rla3hhc4GRWARePP7BWk70WI',
    appId: '1:305841926252:web:dcc3b109e0297ee478a849',
    messagingSenderId: '305841926252',
    projectId: 'onyx-auction-app',
    authDomain: 'onyx-auction-app.firebaseapp.com',
    storageBucket: 'onyx-auction-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGgByWzn-O8Ll05JDX581JVHfi2THFb4g',
    appId: '1:305841926252:android:461cabbc70a24e1178a849',
    messagingSenderId: '305841926252',
    projectId: 'onyx-auction-app',
    storageBucket: 'onyx-auction-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1xd4pgqp11nbu8EvM1zlQUxhWb5iAK7Q',
    appId: '1:305841926252:ios:7b780ab1ce1db2ad78a849',
    messagingSenderId: '305841926252',
    projectId: 'onyx-auction-app',
    storageBucket: 'onyx-auction-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1xd4pgqp11nbu8EvM1zlQUxhWb5iAK7Q',
    appId: '1:305841926252:ios:7b780ab1ce1db2ad78a849',
    messagingSenderId: '305841926252',
    projectId: 'onyx-auction-app',
    storageBucket: 'onyx-auction-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWmaSWoh0rla3hhc4GRWARePP7BWk70WI',
    appId: '1:305841926252:web:3120e4367333d37a78a849',
    messagingSenderId: '305841926252',
    projectId: 'onyx-auction-app',
    authDomain: 'onyx-auction-app.firebaseapp.com',
    storageBucket: 'onyx-auction-app.firebasestorage.app',
  );

}